//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECG_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ecg
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ecg()
        {
            this.ecg_detalle = new HashSet<ecg_detalle>();
        }
    
        public decimal ecg_id { get; set; }
        public System.DateTime fecha_estudio { get; set; }
        public string digitado_por { get; set; }
        public Nullable<decimal> paciente_id { get; set; }
        public Nullable<bool> pediatrico { get; set; }
        public Nullable<decimal> motivo_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ecg_detalle> ecg_detalle { get; set; }
        public virtual paciente paciente { get; set; }
        public virtual motivos_visita motivos_visita { get; set; }
    }
}
