//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECG_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ecg_detalle
    {
        public decimal ecg_det_id { get; set; }
        public Nullable<decimal> ecg_id { get; set; }
        public Nullable<decimal> ritmo_id { get; set; }
        public string deriv_di_ondap { get; set; }
        public string deriv_avf_ondap { get; set; }
        public Nullable<bool> ondap_antes_qrs { get; set; }
        public Nullable<bool> seq_pqrs_todos_complejo { get; set; }
        public Nullable<decimal> duracion_ondap { get; set; }
        public Nullable<decimal> amplitud_ondap { get; set; }
        public Nullable<decimal> intervalo_pr { get; set; }
        public string deriv_di_qrs_r_u_s { get; set; }
        public string deriv_avf_qrs_r_u_s { get; set; }
        public Nullable<bool> complejos_qrs { get; set; }
        public Nullable<decimal> morfologiaqrs_id { get; set; }
        public Nullable<decimal> duracion_qrs { get; set; }
        public Nullable<decimal> amplitud_r_v1_v2 { get; set; }
        public Nullable<decimal> amplitud_s_v1_v2 { get; set; }
        public Nullable<decimal> amplitud_r_v5_v6 { get; set; }
        public Nullable<decimal> amplitud_s_v5_v6 { get; set; }
        public Nullable<decimal> intervalo_qt { get; set; }
        public Nullable<decimal> r_r { get; set; }
        public Nullable<bool> st_isoelectrico { get; set; }
        public string onda_t_v1_v2 { get; set; }
        public string onda_t_v5_v6 { get; set; }
        public Nullable<bool> presencia_onda_q { get; set; }
        public string pico_mas_alto_en { get; set; }
        public Nullable<decimal> profundida_ondaq { get; set; }
        public Nullable<decimal> duracion_ondaq { get; set; }
        public Nullable<bool> supradesnivel_st { get; set; }
        public string supradesnivel_st_en { get; set; }
        public Nullable<bool> infradesnivel_st { get; set; }
        public string infradesnivel_st_en { get; set; }
        public string qrs_isodifasico_en { get; set; }
        public string predominio_s_r_en { get; set; }
        public string predominio_s_r_val { get; set; }
        public Nullable<bool> observa_aleteo_auricular { get; set; }
    
        public virtual ecg ecg { get; set; }
        public virtual ecg_ritmo ecg_ritmo { get; set; }
        public virtual morfologia_qrs morfologia_qrs { get; set; }
    }
}
