//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECG_DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EcgEntities : DbContext
    {
        public EcgEntities()
            : base("name=EcgEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<motivos_visita> motivos_visita { get; set; }
        public virtual DbSet<paciente> pacientes { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<ecg> ecgs { get; set; }
        public virtual DbSet<ecg_detalle> ecg_detalle { get; set; }
        public virtual DbSet<ecg_ritmo> ecg_ritmo { get; set; }
        public virtual DbSet<morfologia_qrs> morfologia_qrs { get; set; }
    }
}
