//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECG_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class motivos_visita
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public motivos_visita()
        {
            this.ecgs = new HashSet<ecg>();
        }
    
        public decimal motivo_id { get; set; }
        public string motivo { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> ultima_actualizacion { get; set; }
        public string usuario_ultima_actualizacion { get; set; }
        public bool activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ecg> ecgs { get; set; }
    }
}
